# Generated by Django 5.2.6 on 2025-10-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categories',
            table='category',
        ),
    ]
